### ISSUE TITLE
Invalid App reference 841165954 when following 'lending pool example'

### ISSUE THREAD

**Issue by flaneur66** [Algofiorg/algofi-python-sdk#41]
When I run the lending_pool_example in order to swap usdc into stbl2 I get the following error:
********************************
   raise error.AlgodHTTPError(e, code)
algosdk.error.AlgodHTTPError: TransactionPool.Remember: transaction YUDHH4FUSVJWYFCCYPZ7JP4CDRVM356C63EUYAH3UWPFFBWRK45A: logic eval error: invalid App reference 841165954. Details: pc=1155, opcodes=bytec 8 // "pool_manager_app_id"
app_global_get
itxn_field Applications

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\y", line 76, in <module>
    txn.submit(client.algod)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\algofipy\transaction_utils.py", line 144, in submit
    raise Exception(str(e))
Exception: TransactionPool.Remember: transaction YUDHH4FUSVJWYFCCYPZ7JP4CDRVM356C63EUYAH3UWPFFBWRK45A: logic eval error: invalid App reference 841165954. Details: pc=1155, opcodes=bytec 8 // "pool_manager_app_id"
app_global_get
itxn_field Applications
**********************************
Code producing the error:
********************************
import os
import algosdk
from algosdk import mnemonic, account
from algosdk.v2client.algod import AlgodClient
from algosdk.v2client.indexer import IndexerClient
from dotenv import dotenv_values

from algofipy.algofi_client import AlgofiClient
from algofipy.globals import Network
from algofipy.amm.v1.amm_config import PoolType, PoolStatus
from algofipy.amm.v1.asset import Asset
from algofipy.transaction_utils import wait_for_confirmation, get_payment_txn, get_default_params
from algofipy.utils import create_asset_transaction
from algofipy.interfaces.lending_pool_interface import PERMISSIONLESS_SENDER_LOGIC_SIG
from algofipy.interfaces import lending_pool_interface, interface_client

mnemonic = "..........................................................................."
key = algosdk.mnemonic.to_private_key(mnemonic)
sender = algosdk.account.address_from_private_key(key)

algod = AlgodClient("", "https://node.algoexplorerapi.io", headers={"User-Agent": "algosdk"})
indexer = IndexerClient(indexer_token="", indexer_address=" https://mainnet-idx.algonode.cloud", headers=None)
client = AlgofiClient(Network.MAINNET, algod, indexer)

user = client.get_user(sender)

lending_pool_app_id = 841198034
lending_pool = client.interfaces.lending_pools[lending_pool_app_id]

swap_in_asset_id = 31566704 #usdc 
swap_in_amount = 10
quote = lending_pool.get_swap_exact_for_quote(swap_in_asset_id, swap_in_amount)

max_slippage = 0.02

txn = lending_pool.get_swap_txns(user, quote, max_slippage)
txn.sign_with_private_keys([key]*2 + [PERMISSIONLESS_SENDER_LOGIC_SIG]*4, [False]*2+ [True]*4)
txn.submit(client.algod)

**Comment by johnclarke96** [comment]
Hi, I addressed this in a recent PR. Let me know if you are good on your side.

**Comment by flaneur66** [comment]
I have not seen you write about this issue. Where can I find it?
